README.md
Adding a user story where organizers can see the attendance rate of the participants. There's a time where the seat is limited but got lots of people in waiting list. At the event day, some people doesn't come without a proper notice. This is a loss as there are some people that way more eager to join but probably got late notice of the event.
With attendance rate we can utilize it to message the participants that their attendance rate is low and the impact is that if it reach some point it will make them to not automatically accepted to get a seat on the event.
The acceptance should be manually triggered by the organizers instead of automatically by system (where if the seats is available then he/she will automatically get the seat)
=> Adding a story where organizers can see participants attendance rate

README.md
- Add links to tech stack items
- Minor typo
=> docs: Improvement to README

data/ddl.sql
Adds `description`, `starts_at`, and `ends_at` to `Events`.
=> Add description, ends_at, starts_at to Event

README.md
This adds recommended terminology to the documentation and could close #58.
=> Add terminology to the README

README.md
1. You have read the contribution guidelines: Yes
2. Your pull request uses a descriptive title: Yes
3. Your pull request targets the master branch of chapter: Yes
4. Closes: Nothing, but shouldn't conflict with #61 either. May conflict with the README changes in #66 
Simple links to issues which have momentum and good titles where we can send frequent questions on these topics.
=> Add Quick Links to the Readme for Accessibility, Shared Profile Data & Auth, and Discovery and Searching Across Collective Instances

docs/api/APIv1.md, docs/organzing groups and events/groups-and-events.md, docs/policies and community guidelines/policies.md, docs/technical issues/technical-issues.md, docs/using chapter/using-chapter.md
This PR does not close an issue
This PR adds folder organization and starter documents so that docs can start to be written.
=> create organized folders and starter docs files

README.md
Quick formatting change to the Contributing section in the README - "Contribute" shouldn't be capitalized here, and the sentence shouldn't be in a header like this.
=> Format Contributing section in README

README.md
User story (participant) edited for clarity, added periods (full stops) and back ticks to terminology in organizer user story. These are simple language edits for clarity in the README.md.
=> docs: edited README.md for clarity (language edit) and add backticks to user story

README.md
Since in the DB we have user email/password and social providers we need to add the user stories for the auth flow.
I'm proposing the smallest set of features I can think of to the auth flow to the MVP. I'm proposing to only use Github as a social provider to minimise things and also I think for now we can only target developers (or aspiring ones!) working on the MVP :)
=> Add stories related to auth flow

README.md
Its a doc change.
1.Case change for letter Women who Code to Women Who Code.
2.freecodecamp link added in one line.
=> link https://www.freecodecamp.org added, case change in doc

docs/how-to-open-a-pull-request.md
Fixed grammatical error in how-to-open-a-pull-request.md
Line 34: 
- Fill in the details as they seem fit you. This information will be reviewed and decide whether or not, your pull request is going to be accepted.
changed to:
- Fill in the details as they seem fit to you. This information will be reviewed and a decision will be made whether or not your pull request is going to be accepted.
=> docs: fix typo/grammar in how-to-open-a-pull-request.md

.github/workflows/ci-workflow.yaml
Closes #XXXXX
Description of changes
- Integrated github action for CI
=> Add github ci workflow

README.md
The schema diagram is huge! Proposing moving into a dropdown like this to save space.
_courtesy https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61_
=> Put schema diagram in a dropdown

README.md
I found a small typo in README.
`opreating` should be  `operating `.
=> fix(docs): small typo in readme

.github/workflows/ci-workflow.yaml
I'm proposing to add a linter stage to our CI build as suggested in this comment: https://github.com/freeCodeCamp/chapter/pull/134#issuecomment-545598705
=> Add lint stage in CI

pages/_document.tsx
<App> is JSX and required react ins cope.
Fixes CI errors
=> fix(_document.tsx): add react to scope of file

.eslintrc.json, package-lock.json, types/models.d.ts
Adds a models.d.ts file for database types.
=> add data models typescript interfaces

CONTRIBUTING.md, README.md
Closes #167 
No effect as it's just updating links in documentation
=> added welcome discord link

README.md, env.sample
=> Updated documentation & fix small error with environment variables

README.md
Closes: nothing
- Change Sequelize to TypeORM
- Vision statement link to the Wiki vision page
- Reword terminology section based on suggestions from confusioned Github members
- Update post-MVP / Roadmap to link to the GitHub Roadmap tag
- Move the API spec below the Tech Stack and Development Setup since seeing the API spec requires these earlier steps
- Change NYC to New York City for clarity
- Add credit DBeaver for the ER Diagram image
=> Docs: Update README: Tech Stack; Links for Vision, MVP, Roadmap; Clarify terminology

README.md
Hello 👋 , haven't checked in on this project in awhile.  Pulled things down again and updated.  Was reading through the `README.md` and code reading a bit to get up to speed.
Made a small change to the readme that creates a terminology table.   To my mind this helped me read and assimilate the information more clearly.  Thought I'd open a PR and if it's useful you all can let me know/ pull it in...  I'll keep reading to see where else I can slot in.
And no worries if it doesn't make sense.
Cheers 🍻
=> fix(docs): README - organize terminology into a table

ormconfig.json, package-lock.json, package.json, server/docs/README.md, server/factories/chapter.factory.ts, server/seeds/chapter.seed.ts
Closes #288
As requested in #288, a scalable implementation of seeding has been added. Added a seed and factory for `Chapter` as an example.
=> Add seed script

server/controllers/chapterController.ts, server/factories/chapter.factory.ts, server/factories/location.factory.ts, server/factories/user.factory.ts, server/migrations/1576447198865-MakePasswordDigestNullable.ts, server/models/Chapter.ts, server/models/User.ts, server/seeds/1_user.seed.ts, server/seeds/2_location.seed.ts, server/seeds/3_chapter.seed.ts, server/seeds/chapter.seed.ts
Cleaning up seeds, and "finishing" chapter api from #105 
Closes #105
=> Add chapter CRUD API

server/models/Chapter.ts, server/models/Event.ts, server/models/Location.ts, server/models/SocialProvider.ts, server/models/Sponsor.ts, server/models/Tag.ts, server/models/User.ts, server/models/UserBan.ts, server/models/UserChapter.ts, server/models/Venue.ts
As discussed in Zeko's stream last night, this fixes the typings for the models, where previously the relationship properties were marked as optional.
=> chore(models): Update models so typeorm relationships are not optional

README.md
Closes: nothing, just a README update
=> Clarify the vocabulary for user, visitor, administrator, organizer, and member in the README

README.md
=> docs: Update copyright year in README

package-lock.json, package.json, server/index.ts
=> Add Swagger UI Express in place of speccy

server/migrations/1582144372565-FixChapterRoleRelation.ts, server/models/User.ts, server/models/UserChapterRole.ts
UserChapterRole was related to 2 users instead of one user and one chapter
=> Fix chapterRole relation error error

server/index.ts, server/migrations/1582144372565-FixChapterRoleRelation.ts
=> Fix db error and a missing function call

.eslintrc.json, server/testUtils/App.ts, types/.eslintrc, types/expressUser.d.ts
This PR allows us to mock users for testing.  For example, a test might say:
```javascript
const app = new App();
// beforeAll
await app.initialize({ withRouter: routerWithAuthedRoutes });
// in test
app.login(someUser);
app.request.get('/blahblah');
expect('something').toBe('something');
app.logout(someUser);
```
=> testing utils for users

data/ddl.sql, server/migrations/1583094753528-RemovePasswordDigest.ts, server/models/User.ts
=> Remove password_digest from User model

README.md
Closes #357
Changes have been made to update the read me with the correct node version.
=> fix(docs): update node version

package-lock.json
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [] My pull request targets the `master` branch of Chapter.
Closes #XXXXX
=> Add back package-lock.json

.dockerignore, Dockerfile, client/.dockerignore, client/Dockerfile, client/package-lock.json, docker-compose.yml
Closes #375
I created separate docker images for the app and the client.
=> fix: update docker setup to build client and start all services in compose

.prettierrc.js, .prettierrc.json
Move from a `js` to `json` file for prettier config to have nice autocomplete
=> Change from prettier.js -> prettier.json

README.md
Changed PR from @pdotsani suggestions in  #402 
This change includes an inline comment next to the `npm install` for a description.
Tested locally and inline comment is ignored.
=> Document: changed README.md to include npm install for client

client/src/components/PageLayout/Header.tsx
This reverts commit 942f802322d4e80b1ba90e41c4754145ee33e6d7.
The reverted commit is captured in the `feat/search` branch.  Once feature complete, the `feat/search` branch will then be merged to master.
=> Revert "Mock search bar with Material UI. refs #349 (#409)"

client/src/modules/home/shared/components/Layout.tsx, client/src/modules/search-results/index.tsx, client/src/pages/search-results.tsx
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
Closes #XXXXX
This is the next iteration after #409. The next PR will make the search bar go to the Search Result Page (a.k.a. SERP).
You can reach it via `/search-results` (we can make it `/search` if you want).
What's missing is the backend functionality (i.e. #349).
=> Create dummy SERP.

.gitpod.yml, client/src/pages/_app.tsx
This configuration should set up everything needed to run and edit the site in Gitpod.
Closes #384
=> feat: add Gitpod configuration

CONTRIBUTING.md, Dockerfile, client/Dockerfile, client/package.json, client/src/modules/dashboard/Events/components/EventFormUtils.ts
=> Updated Docker files to use alpine-14 in line with the recent update.

CONTRIBUTING.md, README.md
Closes #443 
- Changed Discord links in README and CONTRIBUTING to point to the [new fCC chat](https://chat.freecodecamp.org/channel/chapter). 
- Changed the formatting of the "Chapter" name to distinguish it from the "chapter" terminology word
- Removed some old, non longer relevant content
- Minor formatting tweaks
=> Update docs with new chat link, formatting, and up-to-date content

index.html
This PR is just to test the contributor workflow for docs changes to our github page site.
=> Add link to our github

client/src/modules/dashboard/Events/components/EventItem.tsx
Closes #450
Build failed due to:
```bash
npm run lint
```
Removed the ` }) ` from line 66 and now the build succeeds.
=> fix(event): remove extraneous }) to allow build success

CONTRIBUTING.md
* Fix PostgreSQL Manual Mode port to 5432
* Make .env filename consistently italics
* Minor wording changes
=> Fix PostgreSQL port to 5432. Make .env Consistent. Word Tweaks

CONTRIBUTING.md
Adds a manual table of contents for quick links to jump down the document.
=> Add Table of Contents to CONTRIBUTING.md

CONTRIBUTING.md
* Adds notes and improved the docs for Windows / Git for Windows / Git Bash users to start addressing #465 @paizle
* Added a **.env Configuration File** section and link to it to avoid confusion with .env and .env.example like in #462 @NorthDecoder 
* Made commands, command line output, and italics text consistent in the various sections
* Fix typos noted in #447 
* Format "Note:" text consistently
* Made "Prerequisite" software bold and consistent.
* Added better OS-specific notes and links for downloading Git, Docker, and Node.js
Edit(Oliver): 
Closes #465 
Closes #462
I hope that edit is okay, @allella.  I wasn't sure it closed 447, so I left that alone.
=> Docs: Add Windows notes, .env section, make formatting consistent, fix typos to CONTRIBUTING.md

client/src/components/Form/Fields.tsx, client/src/components/ProgressCardContent.tsx, client/src/constants/DashboardLinks.ts, client/src/constants/Header.ts, client/src/modules/dashboard/Events/components/Actions.tsx, client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/components/EventFormUtils.ts, client/src/modules/dashboard/Events/components/EventItem.tsx, client/src/modules/dashboard/Events/pages/EditEventPage.tsx, client/src/modules/dashboard/Events/pages/NewEventPage.tsx, client/src/modules/dashboard/Venues/components/VenueForm.tsx, client/src/modules/dashboard/Venues/components/VenueItem.tsx, db/generator/setupRoles.ts, server/app.ts, server/models/Venue.ts, server/ts/gql.ts
Related to https://github.com/freeCodeCamp/chapter/pull/473.  If this is merged, the CI should pass the lint step.
=> fix: lint errors

client/src/modules/home/index.tsx
Fixes the error that @NorthDecoder encountered while reviewing https://github.com/freeCodeCamp/chapter/pull/540. `chapter.id` should be unique to each chapter which makes it a good candidate for a React key.
=> fix: add iterator key for home page

.env.example, client/package-lock.json, client/package.json, client/yarn.lock, package-lock.json, package.json, server/app.ts, server/auth/index.ts, server/auth/magicLink/index.ts, server/auth/magicLink/passport.ts, yarn.lock
Closes #437 
- Added authentication API, including isAuthenticated, and authantication via email lnk
- Added UI Components to login, connected components to UI
- Completed Login / Logout flow
=> Passport Magiclink Authentication

CONTRIBUTING.md
The CONTRIBUTING.md had been tweaked in the Windows / WSL terminal shell section.
GitPod has been added as an option for launching a development environment. Added GitPod vs Traditional Dev Environment headings and links in the table of contents.
=> Add GitPod Notes, Improve Dev Shell / WSL Notes in CONTRIBUTING.md

client/src/modules/dashboard/Venues/components/VenueForm.tsx
This is a similar fix to https://github.com/freeCodeCamp/chapter/pull/619, it provides type checked default values to the form.
=> fix: allow venues to be edited 

client/src/components/ChapterCard.tsx, client/src/generated/graphql.tsx, client/src/modules/home/graphql/queries.ts, client/src/modules/home/index.tsx
This makes the landing page a little more like the [mockup](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down)
=> feat(client): add chapters to landing page

client/src/components/LoginRegisterModal.tsx, client/src/components/Modal.tsx, client/src/generated/graphql.tsx, client/src/modules/events/pages/eventPage.tsx
User RSVP flow
```
-> click RSVP
-> if logged in
-> rsvp
-> if not logged in
-> login | register
-> rsvp
rsvp => if RSVPed -> cancel
else      -> join
```
=> Show login if user isn't logged in when trying to RSVP

client/src/generated/graphql.tsx
This should stop the CI complaining.
=> chore: fix lint error

README.md
Closes: nothing
Link to @megajon 's [latest mockups](https://github.com/freeCodeCamp/chapter/issues/445#issuecomment-860116686) in the README.
=> Add megajons mockups to the README

package-lock.json, package.json, server/controllers/Events/resolver.ts
=> feat: email users when they RSVP

client/graphql.schema.json, client/src/generated/graphql.tsx, client/src/modules/dashboard/Events/components/EventFormUtils.ts, client/src/modules/dashboard/Events/graphql/queries.ts, client/src/modules/events/pages/eventPage.tsx, db/generator/factories/events.factory.ts, db/migrations/1625060737729-AddEventImage.ts, server/controllers/Events/inputs.ts, server/controllers/Events/resolver.ts, server/models/Event.ts
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [] My pull request targets the `master` branch of Chapter.
Closes #XXXXX
=> Create event images

client/src/generated/graphql.tsx, client/src/modules/chapters/graphql/queries.ts, client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx, client/src/modules/dashboard/Events/pages/EditEventPage.tsx, db/generator/lib/random.ts, server/controllers/Messages/validators/findDuplicateEmails.ts, server/util/Utilities.ts
- chore: prettify
- fix: broken import
- fix: add missing properties to chapter query
=> fix: lint issues and missing properties

.github/workflows/ci-workflow.yaml, Dockerfile, client/Dockerfile, package.json, scripts/postInstall.js
PRs like https://github.com/freeCodeCamp/chapter/pull/653 were complaining about the mismatch between the lockfile version and npm, so this should reduce the noise and hopefully make building Chapter more reliable.
=> feat: set npm version to 7 (Docker + CI)

.github/workflows/cypress.yaml, client/src/components/PageLayout/Header.tsx, client/src/modules/auth/pages/Login.tsx, cypress.json, cypress/integration/auth/login.js, cypress/integration/auth/register.js, cypress/support/commands.js, package-lock.json, package.json
- refactor: create cy.register
- test: add spec for login flow
=> test: add spec for login

client/src/components/ChapterCard.tsx, client/src/components/EventCard.tsx, client/src/components/PageLayout/Header.tsx, client/src/modules/auth/pages/Login.tsx, client/src/modules/auth/pages/Register.tsx, client/src/modules/chapters/pages/chapterPage.tsx, client/src/modules/events/pages/eventPage.tsx, client/tests/__snapshots__/EventCard.test.tsx.snap, cypress/integration/auth/login.js, cypress/integration/auth/register.js, cypress/integration/events/[eventId].js, cypress/integration/landing.js, cypress/support/commands.js
- refactor: kebab-case the data-cy values
- fix: duplicate heading and h2 -> h1
- test: add spec for landing page links
=> fix: text duplication and add tests

.env.example, .github/workflows/cypress.yaml, .gitpod.yml, CONTRIBUTING.md, ormconfig.js, server/app.ts, server/config/index.ts
It seems more intuitive to have IS_DOCKER be either 'true' or 'false' than 'true' or ''
=> fix: check IS_DOCKER against 'true' rather than ''

client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/pages/NewEventPage.tsx, cypress/integration/auth/login.js, cypress/integration/dashboard/chapters.js, cypress/integration/dashboard/events.js, cypress/integration/dashboard/index.js, cypress/integration/dashboard/venues.js, cypress/plugins/index.js, cypress/support/commands.js, package-lock.json, package.json
There are a couple of small fixes here, too.  The event form now has an aria label and event creation sends the correct data type to the server.
=> test: add spec for event creation

client/src/components/Form/Fields.tsx, client/src/modules/dashboard/Chapters/components/ChapterForm.tsx, client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Venues/components/VenueForm.tsx, cypress/integration/dashboard/chapters.js, cypress/integration/dashboard/events.js, cypress/integration/dashboard/venues.js
- fix: add id to TextField so it labels properly
- fix: make form aria-label dynamic
- test: add spec for chapter creation
- test: add spec for venue creation
The venue and chapter forms are a bit rough, so we should update them when we migrate to Chakra, but at least the functionality has tests now.
=> test: specs for venue+chapter creation

client/src/components/LoginRegisterModal.tsx, cypress/integration/auth/login.js, cypress/integration/auth/register.js, cypress/integration/events/[eventId].js, cypress/plugins/index.js, cypress/support/commands.js
- refactor: use GQL helper for register spec
- fix(a11y): convert register Link to Button
- test: create api only register command
- test: make cy.login talk directly to the api
- test: add RSVP spec
=> test: add rsvp spec

client/src/components/LoginRegisterModal.tsx, cypress/integration/events/[eventId].js
=> feat: allow registration during rsvp

client/src/components/Form/Fields.tsx, client/src/components/ProgressCardContent.tsx, client/src/modules/dashboard/Chapters/components/ChapterForm.tsx, client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx, client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx, client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/pages/EditEventPage.tsx, client/src/modules/dashboard/Venues/components/VenueForm.tsx, client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx, client/src/modules/dashboard/Venues/pages/VenuePage.tsx, cypress/integration/dashboard/events.js
1. Imported the Chakra component
2. Removed the Material Ui component
3. Used the chakra component .
4. Removed the Material UI references from Chapter Page
5. Removed Material UI references from Venue Page
Partial fix for issue #608
Please let me know if the changes are good, I'll make changes for other components as well.
Screenshots of old page vs new Page
Old Page :
New Page :
=> Replaced Material UI references with ChakraUI in All Pages/Components

CONTRIBUTING.md, docker-compose.override.yml, package-lock.json, package.json, server/package.json, server/wait-for
- fix: keep logs when watching ts
- fix: make server wait for db to accept connections
The server waiting matters for new users, since the postgres container has a one-time initialisation step which can mean that the app tries to connect before the 5432 port is open.
=> fix: improve developer experience

.github/workflows/update-gh-pages.yaml, package.json
This action will run on every commit to `main`, rather than requiring any human intervention/possibility of forgetting to update the db.
Related to https://github.com/freeCodeCamp/chapter/pull/639 in that it introduces the same `db:sync` command.
=> feat: add action to publish db docs to gh-pages

.github/workflows/update-gh-pages.yaml
This prevents the action running on forks (where it always fails and triggers email alerts) and cuts some of the logging output.  See: https://github.com/freeCodeCamp/chapter/pull/695#issuecomment-924216356
=> fix: reduce noise from gh pages action

client/graphql.schema.json, client/src/generated/graphql.tsx, client/src/modules/dashboard/Events/components/SendEmailModal.tsx, client/src/modules/dashboard/Events/graphql/queries.ts
Fixes a tiny bug that appears if you regenerate `graphql.tsx`
=> fix: add emailGroups arg to sendEventInvite

client/src/generated/graphql.tsx, client/src/modules/dashboard/Events/graphql/queries.ts, client/src/modules/events/pages/eventPage.tsx, server/src/controllers/Events/resolver.ts, server/src/controllers/UserChapterRole/resolver.ts, server/src/controllers/index.ts
Closes #107 
Features Added:
1. Created a setUserInterestForChapter Mutation and called it when user rsvp to an event
2. Added place holder for unsubscribe link in all the event related emails sent from the chapter.
File wise changes:
1. **server/src/controllers/UserChapterRole/resolver.ts** : Created for setUserInterestForChapter Mutation.
2. **client/src/generated/graphql.tsx**: Created the Type definitions of the setUserInterestForChapter Mutation .
3. **client/src/modules/dashboard/Events/graphql/queries.ts** : Added the client side mutation code. 
4. **client/src/modules/events/pages/eventPage.tsx** : Called the mutation when user rsvp to the Event.
=> Created a setUserInterestForChapter mutation and Added placeholder for unsubscribe

cypress/integration/dashboard/events.js, cypress/support/commands.js, server/db/generator/factories/rsvps.factory.ts, server/src/models/Rsvp.ts
- test: email attendees button
- fix: ensure all three RSVP states are seeded
=> test: invite attendees button

CONTRIBUTING.md
Closes #762
This small suggestion would do until the Wiki is updated accordingly for these edge cases.
=> Update CONTRIBUTING.md - Initializing the Database commands

client/src/components/ChapterCard.tsx, client/src/components/EventCard.tsx, client/src/generated/graphql.tsx, client/src/modules/chapters/graphql/queries.ts, client/src/modules/chapters/pages/chaptersPage.tsx, client/src/modules/events/graphql/queries.ts, client/src/modules/events/index.ts, client/src/modules/events/pages/eventsPage.tsx, client/src/modules/home/graphql/queries.ts, client/src/pages/events/index.tsx, client/tests/EventCard.test.tsx, client/tests/__snapshots__/EventCard.test.tsx.snap, cypress/integration/landing.js
Since the old PR https://github.com/freeCodeCamp/chapter/pull/662 was based off of demo, I cherry-picked and created a new one.
Closes: https://github.com/freeCodeCamp/chapter/pull/662
=> feat: add images to cards

.github/workflows/ci-workflow.yaml, .github/workflows/cypress.yaml, .github/workflows/update-gh-pages.yaml, docker-compose.yml
=> chore: use postgres 14

client/graphql.schema.json, client/src/generated/graphql.tsx, client/src/modules/dashboard/Events/pages/EventPage.tsx, client/src/modules/dashboard/Sponsors/components/SponsorForm.tsx, client/src/modules/dashboard/Sponsors/graphql/queries.ts, client/src/modules/dashboard/Sponsors/index.ts, client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx, client/src/modules/dashboard/Sponsors/pages/NewSponsorPage.tsx, client/src/modules/dashboard/Sponsors/pages/SponsorPage.tsx, client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx, client/src/modules/dashboard/shared/components/Layout.tsx, client/src/pages/dashboard/sponsors/[id]/edit.tsx, client/src/pages/dashboard/sponsors/[id]/index.tsx, client/src/pages/dashboard/sponsors/index.tsx, client/src/pages/dashboard/sponsors/new.tsx, server/db/generator/factories/sponsors.factory.ts, server/src/controllers/Sponsors/input.ts, server/src/controllers/Sponsors/resolver.ts, server/src/models/Sponsor.ts
Closes #727 
1. Added Sponsors tab to the dashboard view.
2. Created CreateSponsor and UpdateSponsor Mutations.
3. Created Create new sponsor and update sponsor form.
4. Created Dashboard datatable sponsor views.
=> Added views for Creating and updating sponsors from dashboard.

client/graphql.schema.json, client/src/components/ChapterCard.tsx, client/src/generated/graphql.tsx, client/src/modules/chapters/graphql/queries.ts, client/src/modules/dashboard/Chapters/components/ChapterForm.tsx, client/src/modules/dashboard/Venues/components/VenueForm.tsx, client/src/modules/home/graphql/queries.ts, cypress/integration/dashboard/chapters.js, cypress/integration/dashboard/venues.js, server/prisma/generator/factories/chapters.factory.ts, server/prisma/schema.prisma, server/src/controllers/Chapter/inputs.ts, server/src/controllers/Chapter/resolver.ts, server/src/graphql-types/Chapter.ts
Closes #800 
1. Updated Chapter and Venue forms to be consistent with other forms.
2. Added Place holders to the forms.
3. Removed the details fields from Chapter form, Chapter Schema , Input types and resolvers
=> Updated the Chapter and Venue forms to be consistent with other forms.

client/src/modules/events/pages/eventPage.tsx, server/src/controllers/Events/resolver.ts
Ref: #796 
1. Added useEffect hook to show the dialog if user is logged in and has not RSVP'd to the event
=> Show confirm dialog automatically if user is logged 

client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
Closes #787 
Added the Missing link to Chapters Page.
=> Added users link to chapters page

server/prisma/generator/factories/events.factory.ts, server/prisma/generator/seed.ts
---
- Changes number of generated events during seeding.
- Partially for convenience, partially related to #788
=> chore: generate more events during seeding

client/src/modules/dashboard/Events/components/EventForm.tsx
This should make it little more obvious what each variable actually refers to.
=> refactor: use less generic names in eventform

client/src/modules/dashboard/Events/components/EventForm.tsx
---
- When event is invite only, displays checked checkbox in the edit form.
=> fix: check invite only checkbox when event is invite only

.gitpod.yml
=> fix: bump gitpod node to today's lts (16)

server/src/controllers/Events/resolver.ts
---
- Creates event in single call.
- `eventSponsorsData` and `userEventRoleData` objects can be moved directly into the `eventData`, if that won't get too noisy. With the `TODO` on the latter having them having them under separate variables might be a bit cleaner for now.
- To test manually, `hasPermission` check on line `261` might need to be commented out.
=> refactor: create event in single call

client/graphql.schema.json, client/src/generated/graphql.tsx, server/prisma/schema.prisma, server/src/controllers/Chapter/resolver.ts
---
- Returns chapter on deletion (this one doesn't seem to be anywhere in UI).
- Makes db cascade related fields.
=> feat: return chapter on deletion

server/src/controllers/Events/resolver.ts
---
- When rsvping return new `rsvp` object, instead of `null`.
=> fix: return new rsvp when rsvping

client/graphql.schema.json, client/src/components/EventCard.tsx, client/src/generated/graphql.tsx, client/src/modules/chapters/graphql/queries.ts, client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/components/EventFormUtils.ts, client/src/modules/dashboard/Events/graphql/queries.ts, client/src/modules/dashboard/Events/pages/EditEventPage.tsx, client/src/modules/dashboard/Events/pages/NewEventPage.tsx, client/src/modules/events/graphql/queries.ts, client/src/modules/home/graphql/queries.ts, client/tests/EventCard.test.tsx, client/tests/__snapshots__/EventCard.test.tsx.snap, server/prisma/generator/factories/events.factory.ts, server/prisma/schema.prisma, server/src/controllers/Chapter/resolver.ts, server/src/controllers/Events/inputs.ts, server/src/controllers/Events/resolver.ts, server/src/graphql-types/Event.ts, server/src/graphql-types/EventTag.ts, server/src/graphql-types/index.ts
Closes #790
---
- Changes tags implementation.
- Updates schema, resolvers, client.
- Modifies tags generation for generated events.
- Adding/changing tags on event creation/edition takes couple steps, as it's needed to obtain `id`s for each tag and/or add them to `tags` table first. This is slightly different comparing to sponsors, where sponsor ids are already available in the form.
- Adds jest test for `EventCard` with tags displayed, updates snapshots.
- Any comments and nitpicks are appreciated.
=> feat: tags rework

client/src/generated/graphql.tsx, client/src/modules/events/graphql/queries.ts
---
- Removes duplicated field from query.
=> chore: remove duplicate field from query

client/tests/getLocationString.test.ts
---
Adds tests for `client/src/util/getLocationString.ts`
=> test: getLocationString util

client/tests/venueType.test.ts
---
- Adds tests for `client/src/util/venueType.ts`
=> test: venueType util

server/tsconfig.json
---
- Removes folder with server tests from compiling.
- Prevents duplicated tests runs - once from `.ts` and once from `.js` files.
- Client doesn't have this issue.
=> fix: don't compile server tests

cypress/integration/dashboard/events.js
---
- Adds test if invitation email contains calendar file.
- With briefly checked contents.
=> test: calendar file in invitation email

scripts/postInstall.js
=> chore: fix typo in postInstall.js

.github/workflows/cypress.yaml, client/babel.config.js, client/package.json, cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json
Related to https://github.com/freeCodeCamp/chapter/issues/786
- Added the packages `@cypress/code-coverage` for code coverage and `babel-plugin-istanbul` for instrumenting the code. The code coverage report will be in the folder cypress-coverage
=> feat(client):add e2e coverage

server/src/controllers/Auth/middleware.ts
Closes https://github.com/freeCodeCamp/chapter/issues/1024
The issue was that the client was sitting patiently waiting for a response that never came.  We might want to expand this and do more with the returned messages, but I think this is okay for now.
=> fix: handle missing users

.gitpod.yml
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request targets the `main` branch of Chapter.
=> fix: install from lockfile in Gitpod

README.md
---
- Fixes link to the contributors section of `README.md`
- Changes badge to not require manual updating (or semi-manual via bot) counter of contributors.
=> fix: all-contributors badge

.github/workflows/update-license.yaml
Closes #978
how do I add co-authors😅🤍
I have added action that targets license and change it's yearly licenses
=> update license action

client/src/modules/dashboard/Venues/pages/NewVenuePage.tsx, client/src/modules/dashboard/Venues/pages/VenuePage.tsx, cypress/integration/dashboard/venues.js
This mirrors the event creation flow and improves the Cypress coverage.
=> fix: visit /dashboard/venues/[id] after creation

client/src/components/EventCard.tsx, client/src/modules/dashboard/Events/components/SendEmailModal.tsx, client/tests/__snapshots__/EventCard.test.tsx.snap, cypress/integration/dashboard/events.js, cypress/integration/events/index.js, server/prisma/generator/factories/events.factory.ts, server/prisma/generator/lib/random.ts, server/src/controllers/Events/resolver.ts
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request targets the `main` branch of Chapter.
Closes #XXXXX
=> test: extend EventCard coverage

server/src/controllers/Events/resolver.ts
=> refactor: remove redundant comment

server/src/controllers/Events/resolver.ts
---
- Uses subscription from _chapter user_ (if exists) for a default subscription of events.
- This means, when user unsubscribes from chapter (not yet implemented), user will be by default painlessly not subscribed for new events.
- I'm leaving TODOs, as I'm assuming some user setting to override if user is subscribed by default still might be useful.
=> feat: default user event subscription with chapter subscription

README.md
This seems to be standard and is picked up by the license update action
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request targets the `main` branch of Chapter.
Closes #XXXXX
=> fix: use (c) as copyright symbol

client/src/modules/dashboard/Events/pages/EventPage.tsx, cypress/integration/dashboard/events/[eventId].js
---
- Fixes behavior when cancelling in modal when confirming waitlist or kicking user.
- Adds tests.
=> fix: handling of cancel

server/src/controllers/Events/resolver.ts
=> feat(client): send email on rsvp confirmation

client/src/modules/dashboard/Events/pages/EventPage.tsx, cypress/integration/dashboard/events/[eventId].js
---
- Slightly reduces duplication in event dashboard.
- Changes are not going too deep, while allowing for easy adding of more `ops`.
=> refactor: reduce user lists duplication

client/src/components/LoginRegisterModal.tsx, client/src/components/Modal.tsx, client/src/modules/dashboard/shared/components/RoleChangeModal.tsx
=> refactor: DRY modals and remove unused code

server/src/controllers/Events/resolver.ts
=> feat: create cancel email body text

client/package.json, client/src/components/Card.tsx, client/src/components/EventCard.tsx, client/src/components/Modal.tsx, client/src/components/PageLayout/Header.tsx, client/src/components/PageLayout/index.tsx, client/src/components/ProgressCardContent.tsx, client/src/modules/auth/store/index.tsx, client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx, client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx, client/src/modules/dashboard/Events/components/EventCancelButton.tsx, client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/pages/EditEventPage.tsx, client/src/modules/dashboard/Sponsors/pages/EditSponsorPage.tsx, client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx, client/src/modules/dashboard/Venues/pages/VenuePage.tsx, client/src/modules/dashboard/shared/components/Layout.tsx, client/src/modules/home/index.tsx, client/src/pages/dashboard/index.tsx, client/tests/__snapshots__/EventCard.test.tsx.snap, package-lock.json
- chore: update react and testing/library react
- chore: update chakra-confirm
- fix: address type errors
=> chore: update react and friends

jest.config.js
=> fix: ignore emitted .test.js files when testing

CONTRIBUTING.md
Closes #471
---
OverAll view: https://github.com/Sboonny/chapter/blob/choreadd-troubleshooting-to-CONTRIBUTING/CONTRIBUTING.md#troubleshooting
<details>
<summary>Images preview</summary>
---
Application errors
---
Linux Docker Troubleshooting
---
Node / NPM Troubleshooting
---
ElephantSQL Troubleshooting
---
General Docker Troubleshooting
---
WSL TroubleShooting
---
Windows Docker TroubleShooting
</details>
=> Chore(markdown): add troubleshooting to contributing.md

client/src/modules/events/pages/eventPage.tsx
I couldn't pin this down via cypress tests, unfortunately, since it was
fairly random.
To reproduce: go to `/events/1` and click reload a few times.  It should eventually navigate to `/events/-1`.
=> fix: glitchy page reload

client/src/modules/dashboard/Events/components/EventForm.tsx, client/src/modules/dashboard/Events/components/EventFormUtils.ts
Since none of the text fields use default values, we might as well remove this.
=> Refactor: drop unused default form values

.lintstagedrc.js, package-lock.json, package.json
- chore: regenerate package-lock
- test: move linting to lintstaged and use eslint
I considered adding `tsc`, but it's painfully slow, so it seems better to rely on CI.
=> chore: eslint during lint-staged

package-lock.json, server/package.json
- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request targets the `main` branch of Chapter.
Closes #XXXXX
=> fix(deps): update prisma monorepo to v3.15.2

.github/CODEOWNERS
With these rules it should be possible to ignore renovate while still getting notifications about other PRs. For example: setting notifications to Participation and @ mentions
=> feat: create CODEOWNERS

package.json
@shootermv could you confirm that this is reseting everything you need it to?  With this script, it shouldn't be necessary to think about anything like `build` or `start` in development.
=> fix: reset the prisma client on clean

package.json
It was not getting to the underlying prisma call anyway.
=> refactor: drop --force-reset from db push

package-lock.json, server/package.json
=> chore(deps): update jsonwebtoken
