freeCodeCamp/chapter

data/ddl.sql

Adapt users to be external ID providers friendly

---

README.md

People very frequently are asking on Discord about topic areas (Mobile, Docs, New Ideas, UX, Translation, etc) so having quick links on the Readme allows us to easily send Discord newbies to a single page that summarizes and gives links to the most frequently referenced issues.

Relocate Quick Links from the Pinned Discourse post. Add Schema heading. Add Project Lead

---

README.md

Proposing a quick change in the README - this will be a self-hosted Docker _container_, not image.

README - Docker image -> Docker container

---

data/ddl.sql

Adds `in_waitlist` column that will help implement a whitelist system as the one that meetup.com has right now.

Add waitlist support in RSVPs

---

data/ddl.sql

https://github.com/freeCodeCamp/chapter/issues/17
> @QuincyLarson Looks like the Event table will need 'capacity' to be added
@QuincyLarson Could you please take a look?
@ScottBrenner, vaibhavsingh97: Previous PR(https://github.com/freeCodeCamp/chapter/pull/62) was messed up for some reason - this should be good

Add capacity to events

---

data/ddl.sql

In the schema `ddl.sql` the table `tags` is being referenced in `events` table before creation and hence applying this SQL via `psql` doesn't work out of the box.

fix: create tags before referencing

---

api/swagger.json
data/ddl.sql

Closes #71
I added the "Category" label to the Chapter schema on both the SQL file and on the JSON file. This makes it easier for the end-user to filter the Chapters by the desired categories, and not only by location. The other changes were spacing added by linter for readability purposes, but I can undo them if necessary.

fix/feat/api/swagger.json fix/feat/data/ddl.sql Added category label of types tring to the schemas closes #71

---

.eslintignore
next.config.js

This PR does the following:
* Uses commonjs imports for `next.config.js` (as `next` doesnt transpile when building)
* ignore `next.config.js` when linting so it doesn't yell at us for using commonjs imports

fix next config syntax and linting

---

.eslintrc.json
package-lock.json
package.json

Fixed two issues:
* The following TS was being thrown:
```
app_1     | ERROR in undefined(undefined,undefined):
app_1     | TS2688: Cannot find type definition file for 'jest'.
```
* Running `npm run lint` would result in some jest functions being flagged as not defined
Solution:
* Add the `eslint-plugin-jest` plugin for files ending in `.test.ts(x)` / `.test.js(x)`.

fix eslint rules for jest

---

README.md

Closes: nothing, just a fix
The previous commit used an absolute path that would always point at the main repo's master branch image, which can cause confusion when someone updates the schema.png on their fork.
Github Markdown is smart enough to convert data/schema.png to a path that's relative to the active fork and branch.

Change the schema image path in the README to a relative path 

---

server/routers/exampleRouter.ts
server/routers/routes/sampleAsyncRoute.ts
server/routers/routes/sampleErroredRoute.ts
server/routers/routes/sampleRoute.ts

This is a followup PR to #128.
I'm proposing an intermediate version between the existing solution and what we have in #128.
We are not introducing objects but we are separating functions in files, so we retain a clean router and smaller route files.
I haven't any strong preference between this or #128, I like both :) Maybe this is just a bit simpler?

Refactor: extract routes in folder

---

README.md

The Docker Compose file format used here is version 3.7:
https://github.com/freeCodeCamp/chapter/blob/af99bb496dea8e5699c68f1bf03796851bdadc16/docker-compose.yml#L1
[This requires version 18.06.0+ of Docker Engine](https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix).
However, the installation instructions link to installing Docker Engine 17.12, **which is incompatible with Docker Compose file format version 3.7!**
This pull request proposes instead linking to the latest release of Docker Engine.
-----

fix(docs) - Docker installation instructions

---

CONTRIBUTING.md
README.md

Closes: Nothing
- Removed Elasticsearch, since Quincy agreed with #32 that no advanced search tech is needed for the early going.
- Removed the stale user stories and referenced the live Github MVP project and #84 for post MVP.
- Remove stale roadmap bullets and linked to the live #47, which has an up-to-date list at the top.
- Added suggested steps before creating a new user story issue.
- Tweaked Docker link to be less verbose.

Update README Based on Roadmap. Remove Stale Information

---

package.json

Closes #165
As discussed in #165 , the `node-typescript` package wasn't being used and was also causing node version conflicts so I have removed it from the project.

Fix: Remove unused node-typescript to fix node version conflicts

---

package-lock.json
package.json

Idle state of dev server was consistently crossing 50-60% of CPU usage, due to the use of `fileWatch` api by `fork-ts-checker-webpack-plugin`.
As per https://blog.johnnyreilly.com/2019/05/typescript-and-high-cpu-usage-watch.html blog, adding `TSC_WATCHFILE` env for dev server, helps reduce CPU usage to 3/5% for idle state of the server.

[Fix] High CPU usage by Typescript File Watch

---

api/swagger.json
data/ddl.sql

This is not ready for review. It's a work in progress. I am updating the database & API schemas to reflect the recent decisions we made:
- Allow multiple tags per event.
- Adding admin as a user role. So now we have three user roles: participants (normal visitors), organizers & admin(s).
Closes #254.

 [WIP] fix(db, api): update database model & API schemas 

---

server/db.ts

Migrations were _not_ running programatically. Specifically, `await connection.runMigrations();` was not doing anything as it did not find any migrations.
This was due to the custom config passed into `createConnection` lacking a `migrations` property. I've went ahead and added this.
Some additional context here: https://github.com/freeCodeCamp/chapter/pull/291

Add migrations to db.ts

---

package-lock.json
package.json
server/controllers/chapterController.ts
server/controllers/eventsController.ts
server/factories/event.factory.ts
server/factories/venue.factory.ts
server/index.ts
server/routes/events.ts
server/seeds/4_venue.seed.ts
server/seeds/5_events.seed.ts
tsconfig.json

Event CRUD API

---

README.md

Closes Nothing.
[See my fork for a visual of the changes](https://github.com/allella/chapter/tree/docs/readme-admin-vs-organizer#terminology).
- The user roles were mixed into the terminology but not well defined.
- the use of the word "admin" in the _chapter_ row was in conflict with [the most recent confirmation of _administrator_ vs _organizer_ permissions](https://github.com/freeCodeCamp/chapter/issues/296).

Update README Terminology to define and split out admin vs organizer terms

---

package-lock.json
package.json

I forgot to remove this when I made the migration to typeORM.

Remove unsued sequelize-cli depend

---

.github/workflows/ci-workflow.yaml

Proposing a quick version bump to the `actions/checkout` version used in the CI workflow - `v2` is the latest.

Bump actions/checkout version

---

jest.config.js
package-lock.json
package.json
server/index.ts
server/testUtils/App.ts

I have been facing this issue due to module-alias lib used for typescript project. This lib doesn't work properly with ts-node and typeorm cli. Issue was raised in TypeORM - here https://github.com/typeorm/typeorm/issues/3645
`tsconfig-paths` solves this issue, by directly aliasing modules from `tsconfig.json`. This relieves us from  maintaining aliases in multiple places (_`package.json` was keeping a duplicate alias map_).
Also, jest doesn't need configuration for aliases anymore, as I have updated `jest.config.js` to get aliases automatically, as mentioned [here](https://github.com/dividab/tsconfig-paths/issues/97)

fix: module-not-found error for typeorm cli

---

package-lock.json

We still have some potential vulnerabilities in speccy, but since it's only used in dev and it's soon going to be replaced with SwaggerUI we can ignore that

Update packages to fix vulnerabilites

---

client/components/AddSponsor.tsx
package-lock.json
package.json

So I accidentally broke the form on AddSponsor when I added MaterialUI, the problem is that `react-hook-form` doesn't store date but read live inputs there was a problem with MaterialUI
[More info](https://stackoverflow.com/a/59005842)

Use wrapper components for material UI form elements

---

server/migrations/1581584876652-UserRoles.ts
server/models/UserChapterRole.ts
server/models/UserInstanceRole.ts

Closes #296
Adds the role tables for chapter roles (member, organizer) and instance roles (admin, owner).

add tables for chapter/instance roles

---

api/swagger.json
server/controllers/locationController.ts
server/factories/location.factory.ts
server/migrations/1581805112048-AddAddressToLocation.ts
server/models/Location.ts
server/routes/v1/index.ts
server/routes/v1/location.ts

Add API for creating/reading/updating/deleting locations

Add locations CRUD api

---

README.md

Documentation. Closes nothing.
The _owner_ role was added via https://github.com/freeCodeCamp/chapter/issues/296
The README was updated to differentiate the _owner_ from the _administrator_. 
Other minor tweaks and examples were updated.

Add the owner role and vocabulary tweaks to the README

---

README.md

Closes: Nothing
The README does not provide much direction or reference for UI / UX so this adds a heading and links to the two main Figma assets and the open UI / UX Github issues.
Quincy suggested adding as a Wiki page, but I think having these links upfront in the README will help the more visual people connect with the direction of the project.
We can build out a full Wiki page or .md file for the front-end if/as there's more than a few links of info.

Add UI / UX section and helpful links to the README

---

README.md

It seemed worthwhile to put this in the initial setup guide, rather than leaving it to the detailed DB docs.  I suspect most contributors will want to be working with a seeded DB, if only to cut out a little noise from the logs.

docs: mention seeding in Development Setup

---

client/src/components/PageLayout/Header.tsx

This will require a call to `makeStyles()` in the future.
Also, the logo is too large when compared to the Prototype.
The spacing could be improved, if the placeholder text would be
shorter.
I'd suggest to apply a Floating Label pattern in the future for
accessibility and UX reasons:
https://csslayout.io/patterns/floating-label
My React + Material UI knowledge isn't strong enough yet to do so
on my own.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
Closes #XXXXX
See above. I mainly oriented myself on [the prototype](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down), but the UI lacks backend functionality.
Since I found other links ending in a 404, I think, it should be „good enough” for now.
A next iteration could be the …

Mock search bar with Material UI. refs #349

---

client/graphql.schema.json
client/src/generated/index.tsx
client/src/modules/dashboard/Events/components/EventFormUtils.ts
client/src/modules/dashboard/Events/components/EventItem.tsx
client/src/modules/dashboard/Events/graphql/queries.ts
client/src/modules/dashboard/Events/pages/EventPage.tsx
db/generator/factories/events.factory.ts
db/migrations/1603576293055-AddUrlColumnToEvent.ts
server/controllers/Events/inputs.ts
server/controllers/Events/resolver.ts
server/models/Event.ts

Closes #381
Added URL field to event model, created migration for new column to be added to event table, updated seeders to generate fake URLs, updated UI to allow read and update on URL.
While working on this I noticed that the form to edit events is creating new events.

feat(client, db): event url

---

package-lock.json
package.json

@dtwilliams10 on Discord informed us about a error on `npx resursive-install`. The issue was with @types/node package being versioned wrongly in package.json. It has been fixed with this PR.

fix(build): npm install failure

---

client/src/generated/index.tsx
client/src/modules/dashboard/Events/graphql/queries.ts
client/src/modules/dashboard/Events/pages/EditEventPage.tsx
client/src/modules/dashboard/Venues/pages/EditVenuePage.tsx

Closes #425
Wrote an update event query, updated the client to use the update event query instead of the create event query on the editEventPage.
Note: I thought this was a bug when I filed the original issue, but it turned out the functionality just hadn't yet been built

Feat(api, client): update events

---

CONTRIBUTING.md

This addresses most of the issues outlined in #447.
The main changes are:
* splitting the "Contributing Code" steps from the "Running the Application" steps
* clearly defining "Docker Mode" versus "Manual Mode" steps
* improving the Database docs
* making it more clear how to view the website and API docs once the app is running
I'm sure there are some typos remaining, but I wanted to get this in front of others for review to make sure the overall direction is agreeable.

Improve Docker Mode, Manual Mode, Node Version, Database, Postegres Sections of CONTRIBUTING.md

---

client/src/modules/dashboard/Events/pages/EventsPage.tsx
client/src/modules/dashboard/Venues/pages/VenuesPage.tsx

npm run build:client was failing as className was not part of the
interfaces for EventItem and VenueItem, but it also wasn't used in those
components so can safely be removed.
Closes #454
Edit: I should have said: it was exactly as @tomnoland pointed out in chat.

fix: remove unused className props

---

jest.config.js
server/tests/Mailer.test.ts
tsconfig.json

Closes #469
This is just a small change, so we can start running tests again.  It's the same solution as @paulywill used in https://github.com/freeCodeCamp/chapter/pull/407, but I figured it was worth separating into its own PR.  It will create conflicts, but I think it's worth getting master into a testable state (and I'll fix any conflicts if we merge this).
Finally, the 'warn's were a bit distracting, so I used stub to hide them.

fix: get tests running

---

.eslintrc.json

- X] My pull request has a descriptive title (not a vague title like `Update README.md`).
- X] My pull request targets the `master` branch of Chapter.
Closes #468 
This PR removes the linter rule that expects interface declaration names to be prefaced with `I`. Instead, it now asserts that they are *not* prefaced with `I`. 
If we would prefer the linter not care either way, I can push a commit to disable the rule instead of removing it.

fix(tools): remove interface rule

---

client/src/components/PageLayout/Header.tsx

Updated the site header to look more like the mockup [here](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=332%3A355&scaling=scale-down).
Swapped the placeholder for the search box with the logo.  Replaced the "search" placeholder with a TextField pre-pended with a search icon. Adjusted the spacing a bit.
Relates to issue #445 and #414. Making some minor style changes to get the app looking more like the mockup for the "Golden Path".

fix: Make the site/app header look more like the mockup

---

renovate.json

PRs like https://github.com/freeCodeCamp/chapter/pull/534 should not be automerging.  This change to the config should prevent that.

fix: get renovate to pin all dependencies

---

client/src/pages/_document.tsx

Removes the warning https://nextjs.org/docs/messages/missing-document-component
The Html component renders <html> with a few additional attributes: https://github.com/vercel/next.js/blob/15133b47ec7bfc413aa068d92fb678626cf47571/packages/next/pages/_document.tsx#L118

fix: use next's Html component

---

renovate.json

Prior to this PR renovate would create PRs for all changes, including ones it would automatically merge.  Since dev input is not necessary for automerged PRs, this changes the config so that they will not be notified either.

fix: make automerges push directly, not create PRs

---

client/src/components/Form/TextArea.tsx
client/src/modules/dashboard/Events/components/EventForm.tsx

The defaultValues get merged with the new form values, so cannot include
anything that is not expected by updateEvent
It's a shame that `data` can be `undefined`.  It would be nice if there were two forms (one for new events and one for updating them), so we could have type safe defaultValues, but this seems reasonable for now.

fix: event dashboard edit bugs

---

server/tests/Resolver.test.ts

Looking at the current tests would suggest keeping all the tests together, i.e. `server/tests` and `client/tests`.
Although it did not take me long I had to dig around to locate the random test in  `server/controllers/Messages/resolver.test.ts`.
I realize this not moving the needle for the MVP other than agreement of placing all the tests in one location.

FIX: moved Resolver test into common server/tests directory

---

server/controllers/Auth/resolver.ts

- feat: send the magic link via email
- feat: wrap the link in an anchor tag
With https://github.com/freeCodeCamp/chapter/issues/445 in mind, this makes the login process a little more natural.

feat: email magic link in development

---

.env.example

This is a simple documentation change.
The JWT_SECRET environment variable needs to be 32 random characters, or more, to function as a [proper secret for the default 256-bit crypto algorithm used with Auth0 and JsonWebToken per the earlier conversation](https://github.com/freeCodeCamp/chapter/issues/604#issuecomment-828792850).
The current example is too short and _administrators_ might set a short secret that reduces the security.
The [default HS256 algorithm is 256-bit](https://github.com/auth0/node-jsonwebtoken#usage) so we need at least 32 characters, but having more than 32 doesn't make things more secure unless we were to change the algorithm to something using 512-bit.
Closes: nothing

Update the .env.example with 32 character example for JWT_SECRET

---

client/src/generated/graphql.tsx
client/src/modules/chapters/graphql/queries.ts
client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
client/src/modules/dashboard/Chapters/graphql/mutations.ts
client/src/modules/dashboard/Chapters/index.ts
client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
client/src/modules/dashboard/Chapters/pages/NewChapterPage.tsx
client/src/modules/dashboard/Venues/components/VenueForm.tsx
client/src/modules/dashboard/shared/components/Layout.tsx
client/src/pages/dashboard/chapters/[id]/edit.tsx
client/src/pages/dashboard/chapters/[id]/index.tsx
client/src/pages/dashboard/chapters/index.tsx
client/src/pages/dashboard/chapters/new.tsx

This is basically a copy-paste of the Venue tab, with a few tweaks to make it work. The /dashboard page is still rather basic.  I didn't try to implement any of @megajon's designs and focused on getting it up and running, rather than looking good.
Nonetheless, it's now possible to edit and update chapters from the dashboard view.  @allella I'd love to get your feedback, even though it's a bit rough.
I based it off of https://github.com/freeCodeCamp/chapter/pull/627, so that I could easily make use of those changes.  Might be easier if we merged that first, or we could just merge this and close that.

feat: add chapters to dashboard

---

.env.example
docker-compose.yml
server/services/MailerService.ts

Closes #XXXXX
Paired with @ojeytonwilliams to accomplish this. 
- Adds the mailhog image to the docker-compose file
- Changes the `host` option to be an environment variable
- Added the `EMAIL_HOST` to the `.env.example` with a default of `localhost` for manual setups
- Added the `EMAIL_HOST` to the docker-compose with a value of `mailhog` to match the Mailhog image name.
- Rebuilt and started docker images with new configuration, confirmed that email flow appears to work as intended.
- Confirmed that behaviour remains as intended with manual setup.

fix: add mailhog to docker

---

.env.example
client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/dashboard/Events/components/Actions.tsx
client/src/modules/dashboard/Events/graphql/queries.ts
client/src/modules/dashboard/Events/pages/NewEventPage.tsx
db/generator/factories/user.factory.ts
db/generator/lib/util.ts
db/generator/setupRoles.ts
server/controllers/Chapter/resolver.ts
server/controllers/Events/resolver.ts
server/models/UserChapterRole.ts

The UI is a bit horrible, but this PR adds another button to /dashboard/events/[id] which sends emails to everyone in that chapter.

feat: email all interested users on event creation

---

.gitpod.yml
client/package-lock.json
client/package.json

Otherwise the client will be denied access to the server.
Prettier is used by `npm run both` from the client, but npm doesn't look in parent directories for executables, so I added it to /client

fix(gitpod): make port 5000 visible

---

client/src/modules/events/pages/eventPage.tsx
cypress/integration/event/[eventId].js
db/generator/factories/rsvps.factory.ts

- fix(seed): guarantee a mixture of waiting and not
- test: add basic cy test for an event page
Also bumps up the first heading to `h1` since it's standard a11y practice.

test: Cypress test for event page

---

.github/workflows/ci-workflow.yaml
.github/workflows/cypress.yaml
.gitpod.yml
CONTRIBUTING.md
client/package.json
scripts/postInstall.js

Rather than using `npx recursive-install` I changed the postInstall script to install the client.  That way we get a friendlier output (Welcome to Chapter, etc) and sufficient to use `npm i` to get up and running.

fix: standardizes installation to just use npm i

---

.github/pull_request_template.md
.gitpod.yml
CONTRIBUTING.md
scripts/pullUpstream.sh

- chore: remove default config for gitpod
- chore: replace s/master/main/g
This updates the docs to minimize any confusion from the rename.
We've been meaning to do this for a while now: https://github.com/freeCodeCamp/freeCodeCamp/issues/40895, https://github.com/freeCodeCamp/chapter/issues/434
As for adding a `develop` branch, we can totally do that. However, as @allella pointed out, that's a separate issue from this rename.
Closes: https://github.com/freeCodeCamp/chapter/issues/434

fix: rename master to main

---

renovate.json

This should avoid conflicted PRs like: https://github.com/freeCodeCamp/chapter/pull/689 and https://github.com/freeCodeCamp/chapter/pull/686/

chore: update renovate to group jest deps

---

client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
client/src/modules/dashboard/Events/pages/EventsPage.tsx
client/src/modules/dashboard/Venues/pages/VenuesPage.tsx
cypress/integration/dashboard/chapters.js
cypress/integration/dashboard/events.js
cypress/integration/dashboard/venues.js

Looking at the likes of https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html it seems to be a standard a11y practice to add aria-labelledby to tables, so this adds them for all the existing dashboard tables.
Thanks to @Zeko369 for the neat library.  It's great that you can pass in the table props and it just works.

feat: add labels for dashboard tables

---

client/src/generated/graphql.tsx
client/src/modules/chapters/graphql/queries.ts
client/src/modules/dashboard/Chapters/Users/index.ts
client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
client/src/pages/dashboard/chapters/[id]/users/index.tsx
cypress/integration/dashboard/chapters/users.js

- feat: add a basic chapter users dashboard
- test: add spec for chapter users dashboard
Related to https://github.com/freeCodeCamp/chapter/issues/98 in that it creates a page where a given chapter's organizers can see the users.
Banning functionality to follow!

feat: make dashboard for users

---

client/src/modules/dashboard/Events/pages/EditEventPage.tsx
cypress.json
cypress/integration/dashboard/events.js
cypress/support/commands.js
package-lock.json
package.json
server/src/controllers/Events/resolver.ts

This emails the users that have RVSP'd whenever the venue is changed.
Currently the tests only check that the venue change happens and that emails about it are sent.  It does not, yet, confirm that only the RVSPs get emailed, but I plan to circle back to that test later.
Closes #663

feat: email users on venue change

---

client/src/modules/dashboard/Events/pages/EventPage.tsx
client/src/modules/events/pages/eventPage.tsx

1. Updated the eventPage.tsx to show the count of rsvp
2. updated EventPage.tsx to show the rsvp count
Closes #101 
1. eventPage.tsx Added VStack and then added count for RSVP heading and Waitlist heading
2. EventPage.tsx if rsvp data exists then show the count of the rsvp data beside the heading .

changes to event/[id] and dashoard/event/[id] pages to show RSVP count of Event

---

.gitpod.yml

npm 6 does not handle the lockfile correctly any more, so we need to require version 7.

fix: require npm 7 in gitpod

---

CONTRIBUTING.md

Update a line in the docs that says npm 6 is required.
We now require npm 7 to work around a lockVersion 1 bug mentioned in https://github.com/freeCodeCamp/chapter/issues/705
Closes #705 
@ojeytonwilliams I know you updated another spot in the docs, but this was a different spot.  Also, I believe you made changes to encourage / force npm 7, so I think that will workaround #705.

docs: Update CONTRIBUTING.md to require npm 7

---

CONTRIBUTING.md

* Update and link to the PR that auto-generates the SchemaSpy on GitHub pages
* Update project leads in the FAQ section
* Add bold to **Step** headings for collapsible areas.
* Update and trim down wording of two FAQs
* Remove the line at the end of Step 2 of Manual Mode and Docker Mode sections since Step 3 says the same and then some
* Change the top table of content anchor links for Manual Mode and Docker Mode to jump to the parent section, since it's not possible for Markdown to jump down the page into a collapses section.

docs: Update SchemaSpy auto-generate notes and Minor Style Changes and Tweaks

---

client/src/generated/graphql.tsx
client/src/modules/dashboard/Events/components/Actions.tsx
client/src/modules/dashboard/Events/components/SendEmailModal.tsx
server/src/controllers/Events/resolver.ts

Closes #99 
i. Server
1. resolver.ts
Modified the sendEventInvite Resolver to take an
emailGroup as optional argument.
ii. Client
1. Added New argument in method definitions in graphql.tsx
2. Created a new Modal component to show the checkboxes for
selecting the group
3. Added a button in Actions components to show the Modal
component

Added functionality to send Email to selected Group of People

---

client/src/modules/dashboard/Events/components/EventForm.tsx
client/src/modules/dashboard/Events/components/EventFormUtils.ts
cypress/integration/dashboard/events.js
server/src/app.ts
server/src/controllers/Events/inputs.ts

Closes #430 
1. Added type prop to input component in the Event form page
2.removed the DefaultValue prop from input component since it is already
getting set via UseForm react hook
3. changed the type of URL and Video URL fields to url
4. Added validation decorators to url and video url fields in **server\src\controllers\Events\inputs.ts** file.
5. Enabled class validations in app.ts

Added frontend Input Field Validations on the EventForm.tsx and Enabled validations in app.ts

---

client/src/generated/graphql.tsx
client/src/modules/chapters/graphql/queries.ts
cypress/integration/dashboard/events.js
cypress/support/commands.js

I had to change the `chapterUsers` query so that it returned _user_chapter_role.interested_ as the tests needed to confirm that only those users gets emailed.  Changing a query for testing purposes doesn't feel great, but we'll need to revisit the GraphQL server when we audit for security and make sure only users with appropriate permissions can make queries.
That is to say, we might need to change things, but not yet.

test: check interested users get invited

---

package.json
renovate.json

Right now renovate pins everything, but pinning `engines` to specific node versions is annoying since node updates often. It should not matter if a dev uses a different minor version locally.
This might not pin exactly as we want, but we could be lucky and the defaults could Just Work.

fix: relax renovate to stop it pinning engines

---

server/src/services/AuthToken.ts
server/tests/Auth.test.ts

Created a test for the `AuthToken.ts`.
- Secret should be 32 or more characters
- The token and code should not be null
- The code should have a length of 8 numbers
- The token should not have expired yet
Discovered by making the test that `expiresIn: '120min',` was not working as intended, `2h` appears to be valid.
The only or caveat I foresee is invoking the `jwt.decode(token)` without any error handling I've seen in examples.

test/AuthToken  

---

client/graphql.schema.json
client/src/components/Form/Input.tsx
client/src/generated/graphql.tsx
client/src/modules/dashboard/Events/components/EventForm.tsx
client/src/modules/dashboard/Events/components/EventFormUtils.ts
client/src/modules/dashboard/Events/graphql/queries.ts
client/src/modules/dashboard/Events/pages/EventPage.tsx
client/src/modules/dashboard/Events/pages/EventsPage.tsx
cypress/integration/dashboard/events.js
schema.graphql
server/db/generator/factories/events.factory.ts
server/src/controllers/Events/inputs.ts
server/src/controllers/Events/resolver.ts
server/src/models/Event.ts

This changes the label for input `video_url` to `streaming_url` as per [chat](https://chat.freecodecamp.org/channel/chapter?msg=zXtACaS3Tch7Xuxu2) and mentoned in #270.
The only outstanding issue, #767, is that [_all_ inputs](https://github.com/paulywill/chapter/commit/7219ba46a96d4b6f5224644158c438f1a10f5962) were set to `isRequired` for the Input component.
Thus, the prop for each input on whether it should be `isRequired` should be passed.
@ojeytonwilliams mentioned to reference [graphql.tsx](https://github.com/freeCodeCamp/chapter/blob/bf8f4f1da83560d055d67f9f85b41ace16e647dc/client/src/generated/graphql.tsx#L59) and check which inputs are _without_ `?` as required and visa versa for optional.

Fix/video_url to streaming_ url label for New Event

---

CONTRIBUTING.md

Closes nothing
Adding a note about the localhost URL where test emails can be viewed since it's not obvious what happens to emails in a dev environment.
This is important since magic links for logging in are captured by Mailhog and necessary to login to the client in dev mode.

Docs: Add a note about the local Mailhog localhost URL to CONTRIBUTING.md

---

client/src/pages/_app.tsx
cypress/integration/auth/login.js
cypress/plugins/index.js
server/src/app.ts
server/src/controllers/Auth/middleware.ts

Instead of just reporting there's an error, this clears the JWT (since it was rejected by the server).  If the JWT has expired, the user is redirected to the login page.  This isn't the best UX, so we should investigate refresh tokens or some other way of silently authenticating.

fix: handle expired and invalid session JWTs

---

CONTRIBUTING.md
README.md

Closes nothing.
Fran had a link to a to-do to convert pages to Chakra, but that's been done.
Added [Oliver's Cypress directory](https://github.com/freeCodeCamp/chapter/issues/786) note to the "Where to Find the Code" section of CONTRIBUTING.md and convert the list to bullets.

Docs: Remove closed Chakra to-do from README. Add Cypress to Where to Find The Code

---

client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
cypress/integration/dashboard/chapters/users.js

Closes #789
---
- Removes button from `dashboard/chapters/<x>/users` page.
- Adds test that `/dashboard/chapters/1/users/new` doesn't exist.

fix(client): remove invite user button

---

.gitignore

---
- Adds to `.gitignore` folders with artifacts created by cypress when running tests.

chore: untrack cypress artifacts

---

client/src/modules/dashboard/Events/components/EventForm.tsx

Closes #781
---
- I tried to be more explicit about what is happening.
- I added `valueAsNumber: true` to registering `sponsors.${index}.id`, at some point `id`s of the sponsors in the `watchSponsorsArray` were starting to be as strings, what was messing up strict comparisons. I don't know why or how strings were making there.
- Default values for type/sponsor weren't touched (yet?), but sooner or later probably should.

fix: prevent duplicating sponsors in ui

---

cypress/integration/dashboard/events.js
server/src/controllers/Events/resolver.ts

Still required:
Related to #100
---
Draft adding sending emails to rsvps when event is cancelled.
- Email is send to rsvps that are not cancelled. That means those confirmed or in waitlist. Note in generated data there might be generated rsvps with `cancelled: true`, but this doesn't seem to be displayed in the client right now.
- I've initially added permission check, similar to one in other resolver, based on `user.user_event_roles`, but as that's going to be handled by authorization I've removed it.

feat: send emails to rsvps on event cancel

---

client/src/modules/dashboard/Events/components/EventForm.tsx
client/src/modules/dashboard/Events/components/EventFormUtils.ts
client/src/modules/dashboard/Events/components/EventSponsorCard.tsx

Still required:
Closes #846
---
- Disables `Add` button, when all existing sponsors are added.
- When adding new sponsor, default sponsor type and sponsor are selected from still available sponsors.
- Available sponsor types and sponsors are limited based on selections in other fields.
- Moves default sponsor types to utils.
- Moves functions getting allowed sponsors, sponsor types to utils.
- Any notes are appreciated.

fix: sponsor fields should not be empty

---

client/src/modules/dashboard/Events/components/Actions.tsx
client/src/modules/dashboard/Events/components/EventCancelButton.tsx
client/src/modules/dashboard/Events/components/EventForm.tsx
client/src/modules/dashboard/Events/components/EventFormUtils.ts

Closes #268
---
- Moves cancelling button to separate component.
- Adds cancelling button to event edit page: [image](https://user-images.githubusercontent.com/60067306/148791341-45cab5e9-1d1e-442a-86be-f2f44dd9a61b.png)
- Any notes are appreciated.

feat: add cancel event button to event edit page

---

client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
cypress/integration/dashboard/chapters.js
server/prisma/schema.prisma
server/src/controllers/Chapter/inputs.ts
server/src/controllers/Chapter/resolver.ts
server/src/graphql-types/Chapter.ts

---
- Creating new chapter adds logged in user as creator.
- `ctx.user` is checked, so there's no complains that `creator_id` might be not set.
- `creator_id` is required in `chapters` model and `ObjectType`. 
- Making `creator_id` required in the `CreateChapterInputs` currently would be erroring, as data passed from client doesn't have currently `creator_id`. I couldn't figure a way, to add `creator_id` from the `ctx`, before type of `data` is checked in the mutation resolver. Some middleware or other `type-graphql` feature?

fix: use logged in user as chapter creator

---

client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/dashboard/Events/graphql/queries.ts
server/prisma/schema.prisma
server/src/controllers/Events/resolver.ts

---
- Fixes not deleting events due to data existing in other related tables.
- Batches deletion in transaction.
- Returns event (id) on event deletion - this will be useful in case of updating cache directly after deletion.

feat: return event on deletion

---

server/prisma/schema.prisma

I'm not 100% convinced we *need* `created_at` or `updated_at`, but this makes sure that `update_at` is automatically changed to the current time whenever a record is altered.
For future reference, it's not correct to use queries like `SELECT * FROM chapters WHERE created_at = updated_at;` to see if a record has been updated, since `created_at` and `updated_at` may differ by a few milliseconds even on a newly created record.  `SELECT * FROM chapters WHERE updated_at <= (created_at + '2 ms');` seems fine, though a wider interval might be wise.

fix: use prisma's updateAt to handle updates

---

server/src/controllers/Events/resolver.ts

---
- Queries `user_event_roles` for organizers, rather than filter roles later.

refactor: query for event organizers directly

---

docker-compose.override.yml

Closes https://github.com/freeCodeCamp/chapter/issues/891
@gikf you were right that this was a workspace issue.  Since a lot of dependencies were pulled up to `/` they weren't available to the containers (which had access to `/client` and `/server`). I'd like to keep using workspaces, but we can always revert (or switch to yarn) if the cons outweigh the pros.
Let me know if this sorts it out on your machine (it shouldn't be necessary to rebuild, just `docker-compose up`).

fix: make root dir available in docker dev

---

client/graphql.schema.json
client/src/generated/graphql.tsx
server/src/graphql-types/Rsvp.ts

---
- Changes `confirmed_at` field in `Rsvp` object type to allow being nullable. Rsvping in client expects rsvp object with `confirmed_at`. For invite only events, new rsvp object has `null` for `confirmed_at`, this results in complaints and error.

fix: allow returning rsvp with null confirmed_at

---

server/src/controllers/Auth/middleware.ts
server/src/controllers/Auth/resolver.ts
server/src/controllers/Events/resolver.ts
server/src/controllers/UserChapterRole/resolver.ts
server/src/prisma.ts

---
- Created as draft, as couple places relies a bit on the current behavior (returning `null` when record is not found). This might need some consideration, if this is indeed wanted change. More about this below.
- Sets Prisma to throw by default when `findUnique` or `findFrist` doesn't find record, instead of returning `null`. [(Reference)](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#rejectonnotfound). Typescript recognizes that, what makes half a dozen checks after the query obsolete.
- There's couple places where logic relies on the returned `null`. Currently if prisma would throw there when record is not found, then instead of simple check, we'd need `try/catch`. With ideally(?) making sure we are catching only not found errors. Because of that, I've …

feat: throw by default on prisma findUnique and findFirst

---

server/src/controllers/UserChapterRole/resolver.ts

---
- Wraps creating user chapter role in `try/catch`.
- When error isn't due to db constraints, re-throws error.

feat: rely on db constraints when creating user chapter role

---

CONTRIBUTING.md

Closes nothing.
I'm getting a new device setup and wanted to install node and npm via nvm, so I too a moment to refine the docs related to NVM.
We had a reference to NVM the earlier _Prepare the Development Environment_ section, but that section is focused on the shell and git commands.
node and npm aren't needed for those git steps, so I renamed the section to _Step 2 - Prepare the Terminal and Git Environment_ and migrated the somewhat duplicate notes about node and nvm to the more focused section of _Running the Application | Step 1 - Install Node.js and Dependencies_.
Expanded the notes section under _Step 1 - Install Node.js and Dependencies_ to show that we recommend nvm, but still list the global install option.
@ojeytonwilliams the only thing I left out in these changes is a note …

Docs: Update nvm, node, and npm notes

---

client/src/modules/dashboard/Events/pages/EventPage.tsx

---
- Replaces standard `<a href` with chakra's `Link` component, on event dashboard.
- Adds prop opening these links in new tab.

chore: use chakra Link instead of `a` element

---

server/prisma/generator/lib/random.ts

This allows the factories to pick randomly from both numeric and string enums.  Previously the events.factory was only creating Physical venues.

fix: handle string enums

---

client/tests/date.test.ts

---
- Adds tests for `client/src/util/date.ts`.
- Might be a bit (or more) overkill, but I wanted tests to hit at least once each month, and show how various date, time configurations will look (mainly if that's 24-hour notation and where zero-padding is used).

test: date util

---

client/src/modules/dashboard/Events/components/Actions.tsx
client/src/modules/dashboard/Events/components/EventCancelButton.tsx
client/src/modules/dashboard/Events/pages/EditEventPage.tsx
client/src/modules/dashboard/Events/pages/NewEventPage.tsx
cypress/integration/dashboard/events.js

---
- Adds refetching of the home page query when event is canceled, created, edited, deleted.
- Adds tests checking refetching for two of these cases: editing and deleting of event. To ensure cache is being used, navigation is done with on-page links, instead of visiting pages directly.
- With data generating, to test two other cases, some additional tinkering is needed to make tests consistent.

fix: refetch home page query on event changes

---

package.json

Closes #999
---
- Waits for server before starting generating graphql files.

fix: wait for server before generating graphql files

---

client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/chapters/graphql/queries.ts
client/src/modules/chapters/pages/chapterPage.tsx
client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
client/src/modules/dashboard/Chapters/graphql/mutations.ts
server/prisma/schema.prisma
server/src/controllers/Chapter/inputs.ts
server/src/graphql-types/Chapter.ts

feat(client): add chat url link to chapters

---

package-lock.json
server/package.json
server/src/controllers/Events/resolver.ts
server/src/services/MailerService.ts
server/tests/Mailer.test.ts

---
- Adds `ical-generator` dependency, for generating iCal files/events.
- Generates iCal file/event with couple of basic fields.
- Adds generated iCal file/event to email invitation.
- I'm not entirely sure on what's the usual convention for referring to iCal calendar files with events. Some name adjusting might be in order.
- Adjusts some basic tests.
- I'll be refactoring `MailerService` constructor, to use single object as an argument, in a separate PR.

feat: add iCal file to email invitation

---

server/reminders/reminders.ts
server/src/controllers/Auth/resolver.ts
server/src/controllers/Events/resolver.ts
server/src/controllers/Messages/resolver.ts
server/src/services/MailerService.ts
server/tests/Mailer.test.ts

---
- Small refactoring, replaces few parameters in `MailerService` constructor with single object.

refactor: use object as parameter in constructor

---

cypress/integration/dashboard/events.js

---
- Stops requiring to force click in cypress. 
- This is achieved by clicking the label, instead of the input. This is one of the possible ways, `cy.findByLabelText` selects the input, `.parent()` goes back to the label itself.

fix: click parent of input

---

.gitignore

---
- Adds `cypress-coverage` folder - containing report artifacts - to `.gitignore`.

chore: don't track cypress-coverage folder

---

client/src/components/LoginRegisterModal.tsx
client/src/modules/auth/pages/Register.tsx
cypress/integration/auth/register.js
cypress/integration/dashboard/chapters.js
cypress/integration/dashboard/chapters/users.js
package.json
server/package.json
server/prisma/generator/resetUsers.ts

---
- Displays toast with success/error when registering.
- Swaps/redirects to the login form after successful registration.
- I've played around a bit with tests, reorganized test checking registration with the same email twice, added script for clearing users (quicker setup).

feat: display visual status of registration

---

server/prisma/generator/factories/events.factory.ts

---
- `cypress/integration/events/index.js` intermittent fails (ie. https://github.com/freeCodeCamp/chapter/runs/6427610818?check_suite_focus=true), test seems to be caused by `/events` displaying only upcoming events. In the rare occurrence of event being seeded as already passed, the number of displayed events will be less.
- Adds one day to the random date of event, ensuring all seeded events are upcoming.
- Some alternative might be changing test seeding from `before` to `beforeEach`, but it might be not ideal to still have seeds for which test can't success.

fix: ensure seeded events are upcoming

---

cypress/integration/events/[eventId].js

---
- Slight tweak to test going a bit spotty recently - https://github.com/freeCodeCamp/chapter/runs/6429048621?check_suite_focus=true.
- As right now modal changes automatically on successful registration, explicit clicking to swap back to login form is not needed.

fix: wait for ui before login try

---

cypress/integration/dashboard/events.js
cypress/support/commands.js
cypress/support/index.d.ts
server/src/services/MailerService.ts

Closes #956
This PR sends all emails with the recipients in the `BCC` field instead of the `To` field. The tests have also been updated to check for it and I've created a custom command for it. 
I was unsure if **every** or only bulk emails should use `BCC` so I went with every mail for now. If it's only for bulk emails then I think the `sendEmail` function will need an extra argument for the case where bulk emails are sent to the event organizers(assuming these recipients are not to be BCCed).

feat: use bcc field to send email

---

server/tests/Mailer.test.ts

This is an addition to #1049 
Because of how important it is to make sure to never leak user email addresses, I think it might make sense to have a unit test to make sure that our own `sendEmail` doesn't send `to` to nodemailer's `sendMail`.
The test mocks `sendMail` and makes sure that the object it receives includes `bcc`, but not `to`.

test: Ensure MailerService's sendEmail uses 'bcc'

---

client/src/components/EventCard.tsx
client/src/modules/dashboard/Events/pages/EventsPage.tsx

Closes #XXXXX
When viewing timestamp data vs the timestamp reflected in the events pages, there is a slight difference in the timestamps. By adding some logic to the input in `formatDate` we can correct this issue without having to modify the way we edit events.

fix: Dates not matching up on all pages

---

client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/chapters/graphql/queries.ts
client/src/modules/chapters/pages/chapterPage.tsx
client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
client/src/modules/dashboard/Chapters/graphql/mutations.ts
client/src/modules/dashboard/Chapters/pages/ChapterPage.tsx
client/src/modules/dashboard/Chapters/pages/EditChapterPage.tsx
client/src/modules/dashboard/Events/components/Actions.tsx
client/src/modules/dashboard/Events/components/EventCancelButton.tsx
client/src/modules/dashboard/Events/components/EventForm.tsx
client/src/modules/dashboard/Events/components/SendEmailModal.tsx
client/src/modules/dashboard/Events/graphql/mutations.ts
client/src/modules/dashboard/Events/pages/NewEventPage.tsx
client/src/modules/events/pages/eventPage.tsx
cypress/support/commands.js
server/src/controllers/ChapterUser/resolver.ts

This is necessary for authorization, since the checker cares about which chapter/event a request wants to affect.  It lacks context about how a variable will be used, so the variable must be named appropriately (`chapterId` if it targets a chapter, `eventId` for events).
It only cares about the variable name, not what the resolver is actually called with, so I normalised them to use `id` as their argument.  For consistency, it's probably an idea to change those too, but I didn't want to do too much in one PR.

refactor: generic $id to named ids

---

client/graphql.schema.json
client/src/generated/graphql.tsx
client/src/modules/events/graphql/mutations.ts
client/src/modules/events/pages/eventPage.tsx
cypress/integration/auth/login.js
cypress/integration/events/[eventId].js
cypress/plugins/index.js
cypress/support/commands.js
server/prisma/generator/factories/chapterRoles.factory.ts
server/prisma/generator/factories/events.factory.ts
server/prisma/generator/factories/instanceRoles.factory.ts
server/src/controllers/Events/resolver.ts
server/tests/testUtils/createSchema.ts

This is a trivial requirement, because all instance members have it and
it might be smarter to modify the authorization checker to allow empty
`Authorized()` decorators, but let's try this approach for now.

feat: require authorization to rsvp

---

server/src/authorization/index.ts
server/src/common-types/gql.ts
server/src/controllers/Auth/middleware.ts
server/src/controllers/Events/resolver.ts
server/src/graphql-types/EventUser.ts
server/src/graphql-types/User.ts
server/tests/authorization.test.ts
server/tests/fixtures/users.ts
server/tests/testUtils/App.ts
server/tests/testUtils/createSchema.ts

With these changes a user that is banned from a Chapter will fail every authorization check for requests related to that Chapter. Users with instance level permissions will not be affected.
While implementing this I also cleaned up the types and made `authorizationChecker` explicitly synchronous.  Since we get the user's data in the _authentication_ middleware, there's no need to query the db during _authorization_.
Cypress tests to follow - I'd like to get https://github.com/freeCodeCamp/chapter/pull/1081 in first.

feat: handle bans in authorization

---

renovate.json

Some of the config was duplicated, but I also dropped the extra
automergeType and prCreation rules. This is motivated by the fact that
renovate is not currently creating PRs.

fix: extend the fcc renovate config
